require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
project 'DemoENV', {
  'DebugDev' => :debug,
  'DebugStaging' => :debug,
  'DebugProd' => :debug,
  'ReleaseDev' => :release,
  'ReleaseStaging' => :release,
  'ReleaseProd' => :release,
}
target 'DemoENV' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'DemoENVTests' do
    inherit! :complete
    # Pods for testing
  end
  #----Pod impor---#
end

target 'DemoENV-tvOS' do
  # Pods for DemoENV-tvOS

  target 'DemoENV-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
